In [1]:
import numpy as np
import pandas as pd

In [46]:
n_states = 9
graph = np.zeros((n_states, n_states))
cost = np.zeros((n_states, n_states))

values = np.zeros((n_states,1))
policy = np.zeros((n_states,1))

In [47]:
#setting the cost of the connections
offset = 1 #to take into account 0 counting

graph[1-offset,2-offset] = 1
cost[1-offset,2-offset] = 1

graph[1-offset,3-offset] = 1
cost[1-offset,3-offset] = 2


graph[2-offset,5-offset] = 1
cost[2-offset,5-offset] = 12


graph[2-offset,4-offset] = 1
cost[2-offset,4-offset] = 6


graph[3-offset,4-offset] = 1
cost[3-offset,4-offset] = 3

graph[3-offset,6-offset] = 1
cost[3-offset,6-offset] = 4

graph[4-offset,5-offset] = 1
cost[4-offset,5-offset] = 4

graph[4-offset,7-offset] = 1
cost[4-offset,7-offset] = 3

graph[4-offset,8-offset] = 1
cost[4-offset,8-offset] = 4

graph[4-offset,6-offset] = 1
cost[4-offset,6-offset] = 15

graph[5-offset,7-offset] = 1
cost[5-offset,7-offset] = 7

graph[6-offset,8-offset] = 1
cost[6-offset,8-offset] = 7

graph[6-offset,9-offset] = 1
cost[6-offset,9-offset] = 15

graph[7-offset,9-offset] = 1
cost[7-offset,9-offset] = 3

graph[8-offset,9-offset] = 1
cost[8-offset,9-offset] = 10


In [48]:
graph

array([[0., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [49]:
cost

array([[ 0.,  1.,  2.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  6., 12.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  3.,  0.,  4.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  4., 15.,  3.,  4.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  7.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  7., 15.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

The question is: find the shortest path from 1 to 9

To  do that we use backward induction

Bellman's equation

$ v(t) = \min_{s>=t+1} c_{ts} + v(s)$

So we have that $v(9)$ is 0, $v(8)= \min {c_{89}}= c_{89}=10$

In [57]:
for i in reversed(range(n_states)):
    possible_values = []
    indexes = []
    for j in range(i,n_states):
        if graph[i,j]==1:
            #print(cost[i,j])
            possible_values.append(cost[i,j]+values[j])
            indexes.append(j)
     
    if len(possible_values)==0:
        values[i]=0
    else:
        #print(f'possible values {possible_values}')
        values[i] = min(possible_values)
        policy[i] = indexes[possible_values.index(min(possible_values))]

In [60]:
values

array([[11.],
       [12.],
       [ 9.],
       [ 6.],
       [10.],
       [15.],
       [ 3.],
       [10.],
       [ 0.]])

In [65]:
policy+1

array([[3.],
       [4.],
       [4.],
       [7.],
       [7.],
       [9.],
       [9.],
       [9.],
       [1.]])

In [74]:
state=0
optimal_path = [state]
while state < n_states-1:
    next_state = int(policy[state][0])
    optimal_path.append(next_state)
    state = next_state
    
[1+i for i in optimal_path]

[1, 3, 4, 7, 9]